export const products = [
  {
    id: 369,
    name: "Edifice (ED369)",
    brand: "Casio",
    type: "Chronograph",
    price: "150.00",
    movement: "Quartz",
    gender: "M",
    popularity: 36,
    rating: 3.5,
    imgs: [
      "https://m.media-amazon.com/images/I/713m0cORTBL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/516UJ9B3AiL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/41ojGD14DkL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/61pU41bIjsL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/51zRqfJICzL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/51dLG6sE23L._UL1100_.jpg",
    ],
    description:
      "Brand New Casio Edifice Tachymeter Chronograph Multi-Color Dial Men's Watch - EF-539D-1AVDF (ED369)",
  },
  {
    id: 61,
    name: "SRPD61K1",
    brand: "Seiko",
    type: "Analog",
    price: "250.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 69,
    rating: 4.2,
    imgs: [
      "https://m.media-amazon.com/images/I/81j8TtonHhL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71WmjI3VosL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71u-C9C5IqL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71zydc1xRpL._UL1500_.jpg",
    ],
    description:
      "Dial Color: Green, Case Shape: Round, Dial Glass Material: Hardlex /n Band Color: Silver, Band Material: Stainless Steel Watch Movement Type: Automatic, Watch Display Type: Analog Case Material: Stainless Steel, Case Diameter: 42.5 millimeters Water Resistance Depth: 100 meters",
  },
  {
    id: 5000,
    name: "Gshock GMWB5000D-1",
    brand: "Casio",
    type: "Digital",
    price: "550.00",
    movement: "Digital",
    popularity: 81,
    gender: "U",
    rating: 4.3,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq1.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq5.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq4.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq8.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "The DW-5000C is the original G-Shock model from 1983. The GMW-B5000 Series has inherited its characteristic square design and been given the full metal treatment along with upgraded features including smartphone linking. The watch has been given a full-metal case by using a shock-resistant fine resin cushioning material inserted between the case and the sturdy stainless steel metal bezel. High-density mounting technology also allows the watch to maintain its size. The back of the watch features a solid Screw Lock Back and has been DLC treated for resistance to wear. The metal band has been dimple processed, inheriting the Resin Band design of the original. Visibility too has been enhanced via use of a film solar cell and STN-LCD (liquid crystal). ",
  },
  {
    id: 930,
    name: "NISMO Limited Edition",
    brand: "Casio",
    type: "Chronograph",
    price: "300.00",
    movement: "Solar",
    gender: "M",
    popularity: 61,
    rating: 3.5,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_top.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_N.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_side.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "Celebrate a motorsports-chronograph partnership born in 2021 with the EDIFICE NISMO Limited Edition. ",
  },
  {
    id: 27086162,
    name: "True Square Automatic Open Heart",
    brand: "Rado",
    type: "Analog",
    price: "2500.00",
    movement: "Automatic & Mechanical",
    popularity: 78,
    rating: 4.0,
    gender: "U",
    imgs: [
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_truesquare_734_6086_3_016_3.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_0173460863016_r27086162_a_2.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_0173460863016_r27086162_b_2.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_r27086162_wrist_a.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
    ],
    description:
      "At Rado, we made our name producing square high-tech ceramic watches. The True Square is a new take on an iconic Rado shape. Our first watch made using a square injected monobloc high-tech ceramic case, the True Square is light, scratch-resistant and comfortable to wear. Distinctive and design-led the Rado True Square Automatic Open Heart is the shape of things to come. ",
  },
  {
    id: 1374101104100,
    name: "PRX T1374101104100",
    brand: "Tissot",
    type: "Analog",
    price: "250.00",
    movement: "Quartz",
    rating: 3.9,
    gender: "M",
    popularity: 76,
    imgs: [
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_1.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_10.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_2.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_8.jpg",
    ],
    description:
      " In 1978 the Tissot PRX was born, in 2021 we celebrate its comeback. The new Tissot PRX, the watch for those with passion for design and an eye for ingenuity. Discover the brand new Tissot PRX now, its evocative and slim design makes it an uncompromising essential for all the design enthusiasts.",
  },
  {
    id: 36,
    name: "DATEJUST 36",
    brand: "Rolex",
    type: "Analog",
    price: "",
    movement: "Automatic & Mechanical",
    gender: "U",
    rating: 4.8,
    popularity: 94,
    imgs: [
      "https://content.rolex.com//dam/2022/upright-cc/m126233-0039.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com//dam/2022/laying-ba-with-shadow/m126233-0039.png?impolicy=v6-corners&sc=0.262&vo=-154",
      "https://content.rolex.com//dam/2022/presentation-box-hr/m126233-0039.jpg?impolicy=v6-corners-bg&sc=0.17",
      "https://content.rolex.com//dam/2022/presentation-tray/m126233-0039.jpg?impolicy=v6-corners&sc=0.32&vo=109",
    ],
    description: " Oyster, 36 mm, Oystersteel and yellow gold",
  },
  {
    id: 466,
    name: "SRZ466P1",
    brand: "Seiko",
    type: "Analog",
    price: "",
    movement: "Quartz",
    gender: "W",
    rating: 3.7,
    popularity: 34,
    imgs: [
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-large.jpg",
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-multiple-2.jpg",
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-multiple-1.jpg",
    ],
    description:
      " Seiko has empowered the upliftment of new ideas and independence alike. Known for creating timepieces that are primarily for men and also unisex, it was new for the brand to launch a line of watches just for women. Called the Seiko Ladies collection, the timepieces under this collection are specifically made for women and cater to the feminine mind with sometimes quirky and sometimes elegant designs.",
  },
];
// {
//     id: ,
//     name: "",
//     brand: "",
//     type: "",
//     price: "",
//     movement: "",
//     gender: "",
//     imgs: [
//         "","","","",
//     ],
//     description:
//       " ",
//   },
