export const products = [
  {
    id: 369,
    name: "Edifice (ED369)",
    brand: "Casio",
    type: "Chronograph",
    price: "150.00",
    movement: "Quartz",
    gender: "M",
    popularity: 36,
    rating: 3.5,
    imgs: [
      "https://m.media-amazon.com/images/I/713m0cORTBL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/516UJ9B3AiL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/41ojGD14DkL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/61pU41bIjsL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/51zRqfJICzL._UL1100_.jpg",
      "https://m.media-amazon.com/images/I/51dLG6sE23L._UL1100_.jpg",
    ],
    description:
      "Brand New Casio Edifice Tachymeter Chronograph Multi-Color Dial Men's Watch - EF-539D-1AVDF (ED369)",
  },
  {
    id: 61,
    name: "SRPD61K1",
    brand: "Seiko",
    type: "Analog",
    price: "250.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 69,
    rating: 4.2,
    imgs: [
      "https://m.media-amazon.com/images/I/81j8TtonHhL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71WmjI3VosL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71u-C9C5IqL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71zydc1xRpL._UL1500_.jpg",
    ],
    description:
      "Dial Color: Green, Case Shape: Round, Dial Glass Material: Hardlex /n Band Color: Silver, Band Material: Stainless Steel Watch Movement Type: Automatic, Watch Display Type: Analog Case Material: Stainless Steel, Case Diameter: 42.5 millimeters Water Resistance Depth: 100 meters",
  },
  {
    id: 5000,
    name: "Gshock GMWB5000D-1",
    brand: "Casio",
    type: "Digital",
    price: "550.00",
    movement: "Digital",
    popularity: 81,
    gender: "U",
    rating: 4.3,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq1.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq5.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq4.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GM/GMW/GMW-B5000D-1/assets/GMW-B5000D-1_Seq8.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "The DW-5000C is the original G-Shock model from 1983. The GMW-B5000 Series has inherited its characteristic square design and been given the full metal treatment along with upgraded features including smartphone linking. The watch has been given a full-metal case by using a shock-resistant fine resin cushioning material inserted between the case and the sturdy stainless steel metal bezel. High-density mounting technology also allows the watch to maintain its size. The back of the watch features a solid Screw Lock Back and has been DLC treated for resistance to wear. The metal band has been dimple processed, inheriting the Resin Band design of the original. Visibility too has been enhanced via use of a film solar cell and STN-LCD (liquid crystal). ",
  },
  {
    id: 930,
    name: "NISMO Limited Edition",
    brand: "Casio",
    type: "Chronograph",
    price: "300.00",
    movement: "Solar",
    gender: "M",
    popularity: 61,
    rating: 3.5,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_top.jpg.transform/main-visual-pc/image.jpg",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_N.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/in/en/timepiece/product/watch/E/EQ/EQS/EQS-930NIS-1A/assets/EQS-930NIS-1A_side.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "Celebrate a motorsports-chronograph partnership born in 2021 with the EDIFICE NISMO Limited Edition. ",
  },
  {
    id: 27086162,
    name: "True Square Automatic Open Heart",
    brand: "Rado",
    type: "Analog",
    price: "2500.00",
    movement: "Automatic & Mechanical",
    popularity: 78,
    rating: 4.0,
    gender: "U",
    imgs: [
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_truesquare_734_6086_3_016_3.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_0173460863016_r27086162_a_2.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_0173460863016_r27086162_b_2.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
      "https://www.rado.com/media/catalog/product/t/r/truesquare_r27086162_wrist_a.png?im=AspectCrop=(1980,1980),allowExpansion,location=(0.5,0.5);Resize=(1980,1980),aspect=fill;Crop=(0,0,1980,1980),gravity=Center",
    ],
    description:
      "At Rado, we made our name producing square high-tech ceramic watches. The True Square is a new take on an iconic Rado shape. Our first watch made using a square injected monobloc high-tech ceramic case, the True Square is light, scratch-resistant and comfortable to wear. Distinctive and design-led the Rado True Square Automatic Open Heart is the shape of things to come. ",
  },
  {
    id: 1374101104100,
    name: "PRX T1374101104100",
    brand: "Tissot",
    type: "Analog",
    price: "250.00",
    movement: "Quartz",
    rating: 3.9,
    gender: "M",
    popularity: 76,
    imgs: [
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_1.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_10.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_2.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1374101104100_8.jpg",
    ],
    description:
      " In 1978 the Tissot PRX was born, in 2021 we celebrate its comeback. The new Tissot PRX, the watch for those with passion for design and an eye for ingenuity. Discover the brand new Tissot PRX now, its evocative and slim design makes it an uncompromising essential for all the design enthusiasts.",
  },
  {
    id: 36,
    name: "DATEJUST 36",
    brand: "Rolex",
    type: "Analog",
    price: "",
    movement: "Automatic & Mechanical",
    gender: "U",
    rating: 4.8,
    popularity: 94,
    imgs: [
      "https://content.rolex.com//dam/2022/upright-cc/m126233-0039.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com//dam/2022/laying-ba-with-shadow/m126233-0039.png?impolicy=v6-corners&sc=0.262&vo=-154",
      "https://content.rolex.com//dam/2022/presentation-box-hr/m126233-0039.jpg?impolicy=v6-corners-bg&sc=0.17",
      "https://content.rolex.com//dam/2022/presentation-tray/m126233-0039.jpg?impolicy=v6-corners&sc=0.32&vo=109",
    ],
    description: " Oyster, 36 mm, Oystersteel and yellow gold",
  },
  {
    id: 466,
    name: "SRZ466P1",
    brand: "Seiko",
    type: "Analog",
    price: "",
    movement: "Quartz",
    gender: "W",
    rating: 3.7,
    popularity: 34,
    imgs: [
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-large.jpg",
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-multiple-2.jpg",
      "https://cdn1.ethoswatches.com/media/catalog/product/cache/6e5de5bc3d185d8179cdc7258143f41a/s/e/seiko-fashion-style-srz466p1-multiple-1.jpg",
    ],
    description:
      " Seiko has empowered the upliftment of new ideas and independence alike. Known for creating timepieces that are primarily for men and also unisex, it was new for the brand to launch a line of watches just for women. Called the Seiko Ladies collection, the timepieces under this collection are specifically made for women and cater to the feminine mind with sometimes quirky and sometimes elegant designs.",
  },
  {
    id: 1001,
    name: "Submariner Date",
    brand: "Rolex",
    type: "Analog",
    price: "9150.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 98,
    rating: 4.9,
    imgs: [
      "https://content.rolex.com/dam/2022/upright-cc/m126610ln-0001.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com/dam/2022/laying-ba-with-shadow/m126610ln-0001.png?impolicy=v6-corners&sc=0.262",
      "https://content.rolex.com/dam/2022/presentation-box-hr/m126610ln-0001.jpg?impolicy=v6-corners-bg&sc=0.17",
    ],
    description:
      "Oyster, 41 mm, Oystersteel. The Oyster Perpetual Submariner Date in Oystersteel with a Cerachrom bezel insert in black ceramic and a black dial with large luminescent hour markers.",
  },
  {
    id: 1002,
    name: "Speedmaster Moonwatch",
    brand: "Omega",
    type: "Chronograph",
    price: "6350.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 95,
    rating: 4.8,
    imgs: [
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-speedmaster-moonwatch-professional-co-axial-master-chronometer-chronograph-42-mm-31030425001001-l.png",
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-speedmaster-moonwatch-professional-co-axial-master-chronometer-chronograph-42-mm-31030425001001-2-product.png",
    ],
    description:
      "The legendary Moonwatch, worn by astronauts during the Apollo missions. Features the Co-Axial Master Chronometer Calibre 3861.",
  },
  {
    id: 1003,
    name: "Khaki Field Mechanical",
    brand: "Hamilton",
    type: "Analog",
    price: "495.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 72,
    rating: 4.4,
    imgs: [
      "https://www.hamiltonwatch.com/media/catalog/product/h/6/h69439931_1.png",
      "https://www.hamiltonwatch.com/media/catalog/product/h/6/h69439931_2.png",
    ],
    description:
      "Inspired by military watches, the Khaki Field Mechanical is a rugged and reliable timepiece with an 80-hour power reserve.",
  },
  {
    id: 1004,
    name: "Tank Solo",
    brand: "Cartier",
    type: "Analog",
    price: "2650.00",
    movement: "Quartz",
    gender: "U",
    popularity: 85,
    rating: 4.6,
    imgs: [
      "https://www.cartier.com/variants/images/44733502582849821/img1/w2560.jpg",
      "https://www.cartier.com/variants/images/44733502582849821/img2/w2560.jpg",
    ],
    description:
      "The Tank watch is a true icon of watchmaking. Introduced in 1917, its design was inspired by the tanks used during World War I.",
  },
  {
    id: 1005,
    name: "Royal Oak",
    brand: "Audemars Piguet",
    type: "Analog",
    price: "23800.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 92,
    rating: 4.9,
    imgs: [
      "https://www.audemarspiguet.com/content/dam/ap/com/products/watches/MTR010055.00/importer/watch.png.transform.appdpng.png",
      "https://www.audemarspiguet.com/content/dam/ap/com/products/watches/MTR010055.00/importer/caseback.png.transform.appdpng.png",
    ],
    description:
      "A legend in luxury watchmaking, the Royal Oak features the iconic octagonal bezel with eight hexagonal screws.",
  },
  {
    id: 1006,
    name: "Navitimer B01",
    brand: "Breitling",
    type: "Chronograph",
    price: "8650.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 79,
    rating: 4.5,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-9a8af0b3c2/ab0138211b1p1-navitimer-b01-chronograph-43-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2a2dca3f61/ab0138211b1p1-navitimer-b01-chronograph-43-702.png",
    ],
    description:
      "The Navitimer is an icon of aviation history. Features the famous circular slide rule for flight calculations.",
  },
  {
    id: 1007,
    name: "Luminor Marina",
    brand: "Panerai",
    type: "Analog",
    price: "7900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 76,
    rating: 4.4,
    imgs: [
      "https://www.panerai.com/content/dam/panerai/products/all-products/watches/luminor-marina/pam01312/pam01312-front.png",
      "https://www.panerai.com/content/dam/panerai/products/all-products/watches/luminor-marina/pam01312/pam01312-back.png",
    ],
    description:
      "The Luminor Marina is the quintessential Panerai, featuring the iconic crown-protecting bridge device.",
  },
  {
    id: 1008,
    name: "Big Pilot's Watch",
    brand: "IWC",
    type: "Analog",
    price: "13500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 81,
    rating: 4.6,
    imgs: [
      "https://www.iwc.com/content/dam/iwc/web/images/collections/pilot-watches/big-pilots-watch/IW329303/IW329303_front.png.transform.global_image_540_2x.png",
      "https://www.iwc.com/content/dam/iwc/web/images/collections/pilot-watches/big-pilots-watch/IW329303/IW329303_back.png.transform.global_image_540_2x.png",
    ],
    description:
      "The Big Pilot's Watch features a distinctive oversized crown and elegant dial, inspired by classic observation watches.",
  },
  {
    id: 1009,
    name: "Monaco",
    brand: "TAG Heuer",
    type: "Chronograph",
    price: "6150.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 83,
    rating: 4.5,
    imgs: [
      "https://www.tagheuer.com/on/demandware.static/-/Sites-tagheuer-master/default/dw1e8b8b5e/TAG_Heuer_Monaco/CBL2111.BA0644/CBL2111.BA0644_1000.png",
      "https://www.tagheuer.com/on/demandware.static/-/Sites-tagheuer-master/default/dw5e3e3e5e/TAG_Heuer_Monaco/CBL2111.BA0644/CBL2111.BA0644_2000.png",
    ],
    description:
      "Made famous by Steve McQueen in the film Le Mans, the Monaco is an icon of racing heritage with its square case.",
  },
  {
    id: 1010,
    name: "Reverso Classic",
    brand: "Jaeger-LeCoultre",
    type: "Analog",
    price: "8050.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 77,
    rating: 4.7,
    imgs: [
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/42/7/2094427.png.crop.1000.1000.png",
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/42/8/2094428.png.crop.1000.1000.png",
    ],
    description:
      "Created in 1931 for polo players, the Reverso features a unique reversible case to protect the dial during matches.",
  },
  {
    id: 1011,
    name: "Seamaster Aqua Terra",
    brand: "Omega",
    type: "Analog",
    price: "5650.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 88,
    rating: 4.7,
    imgs: [
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-seamaster-aqua-terra-150m-omega-co-axial-master-chronometer-41-mm-22010412103001-l.png",
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-seamaster-aqua-terra-150m-omega-co-axial-master-chronometer-41-mm-22010412103001-2-product.png",
    ],
    description:
      "The Aqua Terra collection represents the brand's enduring relationship with the ocean, with a teak-inspired dial pattern.",
  },
  {
    id: 1012,
    name: "Carrera Chronograph",
    brand: "TAG Heuer",
    type: "Chronograph",
    price: "5250.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 80,
    rating: 4.4,
    imgs: [
      "https://www.tagheuer.com/on/demandware.static/-/Sites-tagheuer-master/default/dw1e8b8b5e/TAG_Heuer_Carrera/CBS2210.BA0651/CBS2210.BA0651_1000.png",
      "https://www.tagheuer.com/on/demandware.static/-/Sites-tagheuer-master/default/dw5e3e3e5e/TAG_Heuer_Carrera/CBS2210.BA0651/CBS2210.BA0651_2000.png",
    ],
    description:
      "Named after the Carrera Panamericana race, this chronograph embodies TAG Heuer's racing heritage.",
  },
  {
    id: 1013,
    name: "Presage Cocktail Time",
    brand: "Seiko",
    type: "Analog",
    price: "475.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 74,
    rating: 4.5,
    imgs: [
      "https://m.media-amazon.com/images/I/71nRNs7lR1L._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YnJq8rZpL._UL1500_.jpg",
    ],
    description:
      "The Presage Cocktail Time features a stunning textured dial inspired by Japanese cocktails, with elegant dress watch styling.",
  },
  {
    id: 1014,
    name: "Portugieser Automatic",
    brand: "IWC",
    type: "Analog",
    price: "7650.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 82,
    rating: 4.6,
    imgs: [
      "https://www.iwc.com/content/dam/iwc/web/images/collections/portugieser/iw500714/IW500714_front.png.transform.global_image_540_2x.png",
      "https://www.iwc.com/content/dam/iwc/web/images/collections/portugieser/iw500714/IW500714_back.png.transform.global_image_540_2x.png",
    ],
    description:
      "The Portugieser Automatic 7 Days features an impressive 7-day power reserve and elegant, understated design.",
  },
  {
    id: 1015,
    name: "Master Ultra Thin Moon",
    brand: "Jaeger-LeCoultre",
    type: "Analog",
    price: "12500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 79,
    rating: 4.8,
    imgs: [
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/89/1/2094891.png.crop.1000.1000.png",
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/89/2/2094892.png.crop.1000.1000.png",
    ],
    description:
      "An elegant ultra-thin timepiece featuring a stunning moon phase complication on a minimalist dial.",
  },
  {
    id: 1016,
    name: "Superocean Heritage",
    brand: "Breitling",
    type: "Analog",
    price: "5150.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 75,
    rating: 4.3,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-dc08b7e4a4/ab2030121b1s1-superocean-heritage-b20-automatic-44-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2d3b6e5e5e/ab2030121b1s1-superocean-heritage-b20-automatic-44-702.png",
    ],
    description:
      "A vintage-inspired dive watch combining Breitling's maritime heritage with modern performance.",
  },
  {
    id: 1017,
    name: "Pro Trek PRW-6600",
    brand: "Casio",
    type: "Digital",
    price: "350.00",
    movement: "Digital",
    gender: "M",
    popularity: 65,
    rating: 4.2,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/P/PR/PRW/PRW-6600Y-1A9/assets/PRW-6600Y-1A9.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/P/PR/PRW/PRW-6600Y-1A9/assets/PRW-6600Y-1A9_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "Built for outdoor adventures with Triple Sensor technology, solar power, and atomic timekeeping.",
  },
  {
    id: 1018,
    name: "Ballon Bleu",
    brand: "Cartier",
    type: "Analog",
    price: "6800.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 86,
    rating: 4.7,
    imgs: [
      "https://www.cartier.com/variants/images/44733502582849850/img1/w2560.jpg",
      "https://www.cartier.com/variants/images/44733502582849850/img2/w2560.jpg",
    ],
    description:
      "The Ballon Bleu takes its name from the distinctive sapphire cabochon crown, resembling a balloon floating on water.",
  },
  {
    id: 1019,
    name: "Constellation",
    brand: "Omega",
    type: "Analog",
    price: "5400.00",
    movement: "Automatic & Mechanical",
    gender: "W",
    popularity: 81,
    rating: 4.5,
    imgs: [
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-constellation-omega-co-axial-master-chronometer-29-mm-13110292053001-l.png",
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-constellation-omega-co-axial-master-chronometer-29-mm-13110292053001-2-product.png",
    ],
    description:
      "A refined ladies' timepiece featuring the iconic Constellation design with half-moon facets and a star emblem.",
  },
  {
    id: 1020,
    name: "G-Shock GA-2100",
    brand: "Casio",
    type: "Analog",
    price: "99.00",
    movement: "Quartz",
    gender: "U",
    popularity: 89,
    rating: 4.6,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GA/GA2/GA2100-1A1/assets/GA-2100-1A1.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GA/GA2/GA2100-1A1/assets/GA-2100-1A1_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "The CasiOak, known for its octagonal bezel design. Ultra-slim and lightweight with carbon core guard structure.",
  },
  {
    id: 1021,
    name: "Oyster Perpetual 41",
    brand: "Rolex",
    type: "Analog",
    price: "5900.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 91,
    rating: 4.8,
    imgs: [
      "https://content.rolex.com/dam/2022/upright-cc/m124300-0004.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com/dam/2022/laying-ba-with-shadow/m124300-0004.png?impolicy=v6-corners&sc=0.262",
    ],
    description:
      "The Oyster Perpetual in a striking turquoise blue dial, showcasing the essence of the Oyster concept.",
  },
  {
    id: 1022,
    name: "Prospex Diver's",
    brand: "Seiko",
    type: "Analog",
    price: "550.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 77,
    rating: 4.4,
    imgs: [
      "https://m.media-amazon.com/images/I/81T7CiD0sVL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/81yJqLqKSmL._UL1500_.jpg",
    ],
    description:
      "A professional dive watch with 200m water resistance, inspired by the iconic 1965 Seiko diver's watch.",
  },
  {
    id: 1023,
    name: "Santos de Cartier",
    brand: "Cartier",
    type: "Analog",
    price: "7350.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 84,
    rating: 4.6,
    imgs: [
      "https://www.cartier.com/variants/images/44733502582849912/img1/w2560.jpg",
      "https://www.cartier.com/variants/images/44733502582849912/img2/w2560.jpg",
    ],
    description:
      "Created in 1904 for aviator Alberto Santos-Dumont, the Santos is one of the first modern wristwatches.",
  },
  {
    id: 1024,
    name: "Fifty Fathoms",
    brand: "Blancpain",
    type: "Analog",
    price: "14500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 78,
    rating: 4.7,
    imgs: [
      "https://www.blancpain.com/sites/default/files/styles/product_carousel/public/2023-03/5015-1130-52_front.png",
      "https://www.blancpain.com/sites/default/files/styles/product_carousel/public/2023-03/5015-1130-52_caseback.png",
    ],
    description:
      "The original modern dive watch, created in 1953 for the French Navy combat swimmers.",
  },
  {
    id: 1025,
    name: "Pelagos",
    brand: "Tudor",
    type: "Analog",
    price: "4475.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 80,
    rating: 4.5,
    imgs: [
      "https://www.tudorwatch.com/-/media/tudor/products-new/images/pelagos/m25600tn-0001/m25600tn-0001-gallery-01-m.png",
      "https://www.tudorwatch.com/-/media/tudor/products-new/images/pelagos/m25600tn-0001/m25600tn-0001-gallery-04-m.png",
    ],
    description:
      "A professional dive watch with a titanium case and bracelet, rated to 500 meters water resistance.",
  },
  {
    id: 1026,
    name: "Black Bay Fifty-Eight",
    brand: "Tudor",
    type: "Analog",
    price: "3700.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 85,
    rating: 4.6,
    imgs: [
      "https://www.tudorwatch.com/-/media/tudor/products-new/images/black-bay-fifty-eight/m79030n-0001/m79030n-0001-gallery-01-m.png",
      "https://www.tudorwatch.com/-/media/tudor/products-new/images/black-bay-fifty-eight/m79030n-0001/m79030n-0001-gallery-04-m.png",
    ],
    description:
      "A vintage-inspired dive watch with a 39mm case, paying homage to Tudor's first divers' watches from 1958.",
  },
  {
    id: 1027,
    name: "Pilot Type 20 Chronograph",
    brand: "Zenith",
    type: "Chronograph",
    price: "7500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 71,
    rating: 4.4,
    imgs: [
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/2/9/29.2430.4069-21.c800_1.png",
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/2/9/29.2430.4069-21.c800_2.png",
    ],
    description:
      "A tribute to the historical Type 20 pilot's watches with an onion-shaped crown and oversized Arabic numerals.",
  },
  {
    id: 1028,
    name: "El Primero",
    brand: "Zenith",
    type: "Chronograph",
    price: "9400.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 76,
    rating: 4.6,
    imgs: [
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/0/3/03.3200.3600-69.m3200_1.png",
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/0/3/03.3200.3600-69.m3200_2.png",
    ],
    description:
      "The legendary El Primero, the world's first automatic high-frequency chronograph movement from 1969.",
  },
  {
    id: 1029,
    name: "Chronomat B01",
    brand: "Breitling",
    type: "Chronograph",
    price: "8900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 74,
    rating: 4.5,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-9a8af0b3c2/ab0134101c1a1-chronomat-b01-42-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2a2dca3f61/ab0134101c1a1-chronomat-b01-42-702.png",
    ],
    description:
      "The modern Chronomat featuring Breitling's in-house B01 movement with 70-hour power reserve.",
  },
  {
    id: 1030,
    name: "Master Control Calendar",
    brand: "Jaeger-LeCoultre",
    type: "Analog",
    price: "9850.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 73,
    rating: 4.7,
    imgs: [
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/58/1/2094581.png.crop.1000.1000.png",
      "https://www.jaeger-lecoultre.com/dam/rcq/jlc/20/94/58/2/2094582.png.crop.1000.1000.png",
    ],
    description:
      "An elegant dress watch featuring a triple calendar complication with date, day, and month displays.",
  },
  {
    id: 1031,
    name: "Radiomir",
    brand: "Panerai",
    type: "Analog",
    price: "6900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 70,
    rating: 4.3,
    imgs: [
      "https://www.panerai.com/content/dam/panerai/products/all-products/watches/radiomir/pam00995/pam00995-front.png",
      "https://www.panerai.com/content/dam/panerai/products/all-products/watches/radiomir/pam00995/pam00995-back.png",
    ],
    description:
      "The historic Radiomir, Panerai's original design from 1936, featuring wire lugs and cushion case.",
  },
  {
    id: 1032,
    name: "Overseas",
    brand: "Vacheron Constantin",
    type: "Analog",
    price: "25000.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 83,
    rating: 4.8,
    imgs: [
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/15/4/1666154.png.crop.1000.1000.png",
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/15/5/1666155.png.crop.1000.1000.png",
    ],
    description:
      "A luxurious sports watch with interchangeable straps and the iconic Maltese cross bezel.",
  },
  {
    id: 1033,
    name: "Nautilus",
    brand: "Patek Philippe",
    type: "Analog",
    price: "35000.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 97,
    rating: 4.9,
    imgs: [
      "https://static.patek.com/images/articles/face_702/1920/5711_1A_010_2.jpg",
      "https://static.patek.com/images/articles/face_702/1920/5711_1A_010_1.jpg",
    ],
    description:
      "The legendary Nautilus, designed by Gérald Genta in 1976, featuring the iconic porthole-shaped case.",
  },
  {
    id: 1034,
    name: "Aquanaut",
    brand: "Patek Philippe",
    type: "Analog",
    price: "22000.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 90,
    rating: 4.8,
    imgs: [
      "https://static.patek.com/images/articles/face_702/1920/5167A_001_2.jpg",
      "https://static.patek.com/images/articles/face_702/1920/5167A_001_1.jpg",
    ],
    description:
      "A sporty and modern timepiece with a tropical composite rubber strap and embossed dial pattern.",
  },
  {
    id: 1035,
    name: "Alpine Eagle",
    brand: "Chopard",
    type: "Analog",
    price: "13500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 75,
    rating: 4.5,
    imgs: [
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/2/9/298600-3001_1.png",
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/2/9/298600-3001_2.png",
    ],
    description:
      "Inspired by the St. Moritz, the Alpine Eagle features Lucent Steel A223 and an iris-like dial texture.",
  },
  {
    id: 1036,
    name: "Ingenieur Automatic",
    brand: "IWC",
    type: "Analog",
    price: "9950.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 68,
    rating: 4.4,
    imgs: [
      "https://www.iwc.com/content/dam/iwc/web/images/collections/ingenieur/iw328901/IW328901_front.png.transform.global_image_540_2x.png",
      "https://www.iwc.com/content/dam/iwc/web/images/collections/ingenieur/iw328901/IW328901_back.png.transform.global_image_540_2x.png",
    ],
    description:
      "A sports watch with integrated bracelet, originally designed to protect against magnetic fields.",
  },
  {
    id: 1037,
    name: "Heritage GMT",
    brand: "Longines",
    type: "Analog",
    price: "2450.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 72,
    rating: 4.3,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.748.4.60.0_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.748.4.60.0_2.png",
    ],
    description:
      "A vintage-inspired GMT watch with a rotating bezel and second time zone function.",
  },
  {
    id: 1038,
    name: "HydroConquest",
    brand: "Longines",
    type: "Analog",
    price: "1375.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 67,
    rating: 4.2,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.790.4.56.6_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.790.4.56.6_2.png",
    ],
    description:
      "A sporty dive watch with ceramic bezel, 300m water resistance, and elegant finishing.",
  },
  {
    id: 1039,
    name: "Captain Cook",
    brand: "Rado",
    type: "Analog",
    price: "2150.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 71,
    rating: 4.4,
    imgs: [
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_captain_cook_732_0500_3_120_1.png",
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_captain_cook_732_0500_3_120_2.png",
    ],
    description:
      "A vintage dive watch reissue with modern proportions, featuring a high-tech ceramic bezel insert.",
  },
  {
    id: 1040,
    name: "Gentlemen Powermatic 80",
    brand: "Tissot",
    type: "Analog",
    price: "695.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 69,
    rating: 4.3,
    imgs: [
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1274071104100_1.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1274071104100_2.jpg",
    ],
    description:
      "An elegant dress watch with the Powermatic 80 movement, offering 80 hours of power reserve.",
  },
  {
    id: 1041,
    name: "Bambino Open Heart",
    brand: "Orient",
    type: "Analog",
    price: "275.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 68,
    rating: 4.3,
    imgs: [
      "https://m.media-amazon.com/images/I/71tKJ0lDVxL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71vj3lrZ-DL._UL1500_.jpg",
    ],
    description:
      "An affordable open heart dress watch showcasing the automatic movement through a dial cutout.",
  },
  {
    id: 1042,
    name: "Mako II",
    brand: "Orient",
    type: "Analog",
    price: "195.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 73,
    rating: 4.4,
    imgs: [
      "https://m.media-amazon.com/images/I/81Bj6FLWBZL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/81S3oqfRo-L._UL1500_.jpg",
    ],
    description:
      "A popular automatic dive watch with 200m water resistance and day-date complication.",
  },
  {
    id: 1043,
    name: "Alpinist SPB121",
    brand: "Seiko",
    type: "Analog",
    price: "795.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 82,
    rating: 4.6,
    imgs: [
      "https://m.media-amazon.com/images/I/81RJCcpqYaL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/81I-v1V7O-L._UL1500_.jpg",
    ],
    description:
      "The iconic Alpinist with a green dial and inner compass bezel, built for mountain exploration.",
  },
  {
    id: 1044,
    name: "King Seiko SPB279",
    brand: "Seiko",
    type: "Analog",
    price: "1400.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 74,
    rating: 4.5,
    imgs: [
      "https://m.media-amazon.com/images/I/71J9VqQKKBL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71VKg8DFNVL._UL1500_.jpg",
    ],
    description:
      "The revival of the legendary King Seiko line with modern movements and classic 1960s styling.",
  },
  {
    id: 1045,
    name: "Marinemaster 300",
    brand: "Seiko",
    type: "Analog",
    price: "2900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 79,
    rating: 4.7,
    imgs: [
      "https://m.media-amazon.com/images/I/71WmjI3VosL._UL1500_.jpg",
      "https://m.media-amazon.com/images/I/71u-C9C5IqL._UL1500_.jpg",
    ],
    description:
      "A professional dive watch rated to 300m with Seiko's high-beat automatic movement.",
  },
  {
    id: 1046,
    name: "G-Shock Mudmaster GWG-2000",
    brand: "Casio",
    type: "Analog",
    price: "800.00",
    movement: "Solar",
    gender: "M",
    popularity: 78,
    rating: 4.5,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GW/GWG/GWG-2000-1A1/assets/GWG-2000-1A1.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GW/GWG/GWG-2000-1A1/assets/GWG-2000-1A1_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "Built for extreme environments with mud resistance, Triple Sensor, and Tough Solar power.",
  },
  {
    id: 1047,
    name: "G-Shock Rangeman",
    brand: "Casio",
    type: "Digital",
    price: "350.00",
    movement: "Solar",
    gender: "M",
    popularity: 75,
    rating: 4.4,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GW/GW9/GW-9400-1/assets/GW-9400-1.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/G/GW/GW9/GW-9400-1/assets/GW-9400-1_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "Designed for survival in extreme conditions with Triple Sensor and sunrise/sunset data.",
  },
  {
    id: 1048,
    name: "Baby-G BGA-280",
    brand: "Casio",
    type: "Analog",
    price: "99.00",
    movement: "Quartz",
    gender: "W",
    popularity: 65,
    rating: 4.1,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/B/BG/BGA/BGA-280-4A/assets/BGA-280-4A.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/B/BG/BGA/BGA-280-4A/assets/BGA-280-4A_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "A compact and stylish watch for active women with shock resistance and 100m water resistance.",
  },
  {
    id: 1049,
    name: "Oceanus OCW-T200",
    brand: "Casio",
    type: "Analog",
    price: "650.00",
    movement: "Solar",
    gender: "M",
    popularity: 70,
    rating: 4.4,
    imgs: [
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/O/OC/OCW/OCW-T200S-1A/assets/OCW-T200S-1A.png.transform/main-visual-pc/image.png",
      "https://www.casio.com/content/dam/casio/product-info/locales/us/en/timepiece/product/watch/O/OC/OCW/OCW-T200S-1A/assets/OCW-T200S-1A_1.jpg.transform/main-visual-pc/image.jpg",
    ],
    description:
      "A sleek titanium watch with sapphire crystal, Bluetooth connectivity, and atomic timekeeping.",
  },
  {
    id: 1050,
    name: "Formex Essence 39",
    brand: "Formex",
    type: "Analog",
    price: "1290.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 62,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/Essence-39-Blue-front.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/Essence-39-Blue-side.png",
    ],
    description:
      "A Swiss-made watch with patented case suspension system for superior comfort and shock protection.",
  },
  {
    id: 1051,
    name: "Flieger Classic",
    brand: "Stowa",
    type: "Analog",
    price: "1050.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 66,
    rating: 4.4,
    imgs: [
      "https://www.stowa.de/media/image/c6/8e/9f/FL-KL-SL-BG-L_1.png",
      "https://www.stowa.de/media/image/c6/8e/9f/FL-KL-SL-BG-L_2.png",
    ],
    description:
      "A historically accurate German pilot's watch based on original WWII B-Uhr specifications.",
  },
  {
    id: 1052,
    name: "Nomos Club Campus",
    brand: "Nomos",
    type: "Analog",
    price: "1460.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 69,
    rating: 4.5,
    imgs: [
      "https://nomos-glashuette.com/media/image/64/b9/cd/club-campus-38-night-perspective.png",
      "https://nomos-glashuette.com/media/image/64/b9/cd/club-campus-38-night-back.png",
    ],
    description:
      "A youthful and colorful Bauhaus-inspired watch from the German watchmaking town of Glashütte.",
  },
  {
    id: 1053,
    name: "Tangente",
    brand: "Nomos",
    type: "Analog",
    price: "1850.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 72,
    rating: 4.6,
    imgs: [
      "https://nomos-glashuette.com/media/image/64/b9/cd/tangente-38-perspective.png",
      "https://nomos-glashuette.com/media/image/64/b9/cd/tangente-38-back.png",
    ],
    description:
      "The iconic Bauhaus design that established Nomos as a leader in minimalist German watchmaking.",
  },
  {
    id: 1054,
    name: "Metro Neomatik",
    brand: "Nomos",
    type: "Analog",
    price: "3460.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 68,
    rating: 4.5,
    imgs: [
      "https://nomos-glashuette.com/media/image/64/b9/cd/metro-neomatik-39-perspective.png",
      "https://nomos-glashuette.com/media/image/64/b9/cd/metro-neomatik-39-back.png",
    ],
    description:
      "A modern interpretation with in-house DUW caliber and playful date display at 6 o'clock.",
  },
  {
    id: 1055,
    name: "Max Bill Automatic",
    brand: "Junghans",
    type: "Analog",
    price: "1095.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 73,
    rating: 4.5,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/max-bill-automatic-white.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/max-bill-automatic-white-back.png",
    ],
    description:
      "Designed by Swiss artist Max Bill, a Bauhaus masterpiece with domed glass and minimalist dial.",
  },
  {
    id: 1056,
    name: "Meister Driver Chronoscope",
    brand: "Junghans",
    type: "Chronograph",
    price: "2295.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 64,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/meister-driver-chronoscope.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/meister-driver-chronoscope-back.png",
    ],
    description:
      "A racing-inspired chronograph with retro-style cushion case and tachymeter scale.",
  },
  {
    id: 1057,
    name: "Multifort Patrimony",
    brand: "Mido",
    type: "Analog",
    price: "1050.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 67,
    rating: 4.2,
    imgs: [
      "https://www.midowatches.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/0/m040.407.16.040.00_1.png",
      "https://www.midowatches.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/0/m040.407.16.040.00_2.png",
    ],
    description:
      "A vintage-inspired dress watch with a retro-style dial and 80-hour power reserve.",
  },
  {
    id: 1058,
    name: "Ocean Star 200",
    brand: "Mido",
    type: "Analog",
    price: "950.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 71,
    rating: 4.3,
    imgs: [
      "https://www.midowatches.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/0/m042.430.11.041.00_1.png",
      "https://www.midowatches.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/0/m042.430.11.041.00_2.png",
    ],
    description:
      "A professional dive watch with ceramic bezel and ISO-certified 200m water resistance.",
  },
  {
    id: 1059,
    name: "Everest GMT",
    brand: "Ball",
    type: "Analog",
    price: "3199.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 63,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/ball-engineer-everest.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/ball-engineer-everest-back.png",
    ],
    description:
      "A rugged GMT watch with self-powered micro gas tubes for exceptional low-light visibility.",
  },
  {
    id: 1060,
    name: "Aerospace Evo",
    brand: "Breitling",
    type: "Digital",
    price: "3100.00",
    movement: "Quartz",
    gender: "M",
    popularity: 66,
    rating: 4.2,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-9a8af0b3c2/e79363101b1s1-aerospace-evo-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2a2dca3f61/e79363101b1s1-aerospace-evo-702.png",
    ],
    description:
      "A titanium pilots' watch with ana-digi display, featuring chronograph, alarm, and countdown timer.",
  },
  {
    id: 1061,
    name: "BR 03-92 Diver",
    brand: "Bell & Ross",
    type: "Analog",
    price: "4300.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 70,
    rating: 4.4,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/br03-92-diver-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/br03-92-diver-blue-back.png",
    ],
    description:
      "A square-cased dive watch inspired by aviation instruments with 300m water resistance.",
  },
  {
    id: 1062,
    name: "BR 05 Skeleton",
    brand: "Bell & Ross",
    type: "Analog",
    price: "7900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 65,
    rating: 4.5,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/br05-skeleton-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/br05-skeleton-blue-back.png",
    ],
    description:
      "An urban sports watch with integrated bracelet and skeletonized dial showcasing the movement.",
  },
  {
    id: 1063,
    name: "Clifton Baumatic",
    brand: "Baume & Mercier",
    type: "Analog",
    price: "2990.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 64,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/clifton-baumatic-white.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/clifton-baumatic-white-back.png",
    ],
    description:
      "Features the silicon-regulated Baumatic movement with 5-day power reserve and anti-magnetic properties.",
  },
  {
    id: 1064,
    name: "Riviera Automatic",
    brand: "Baume & Mercier",
    type: "Analog",
    price: "3350.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 62,
    rating: 4.2,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/riviera-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/riviera-blue-back.png",
    ],
    description:
      "A modern sports watch with integrated bracelet, featuring the iconic dodecagonal bezel.",
  },
  {
    id: 1065,
    name: "Heritage Skin Diver",
    brand: "Oris",
    type: "Analog",
    price: "2200.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 72,
    rating: 4.4,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/oris-skin-diver.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/oris-skin-diver-back.png",
    ],
    description:
      "A vintage-inspired dive watch reissue with bronze bezel and 200m water resistance.",
  },
  {
    id: 1066,
    name: "Big Crown Pointer Date",
    brand: "Oris",
    type: "Analog",
    price: "2100.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 69,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/big-crown-pointer-date.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/big-crown-pointer-date-back.png",
    ],
    description:
      "Features the iconic red-tipped pointer date hand, a signature Oris complication since 1938.",
  },
  {
    id: 1067,
    name: "Aquis Date",
    brand: "Oris",
    type: "Analog",
    price: "2350.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 76,
    rating: 4.5,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/oris-aquis-green.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/oris-aquis-green-back.png",
    ],
    description:
      "A professional dive watch with unidirectional ceramic bezel and 300m water resistance.",
  },
  {
    id: 1068,
    name: "Freelancer Chronograph",
    brand: "Raymond Weil",
    type: "Chronograph",
    price: "2995.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 64,
    rating: 4.2,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/freelancer-chrono-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/freelancer-chrono-blue-back.png",
    ],
    description:
      "A sporty chronograph with bi-compax layout and integrated rubber strap.",
  },
  {
    id: 1069,
    name: "Toccata Classic",
    brand: "Raymond Weil",
    type: "Analog",
    price: "850.00",
    movement: "Quartz",
    gender: "M",
    popularity: 58,
    rating: 4.0,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/toccata-classic-white.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/toccata-classic-white-back.png",
    ],
    description:
      "An elegant dress watch inspired by musical harmonies with Roman numerals and slender hands.",
  },
  {
    id: 1070,
    name: "Pilot's Watch Mark XVIII",
    brand: "IWC",
    type: "Analog",
    price: "4450.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 77,
    rating: 4.5,
    imgs: [
      "https://www.iwc.com/content/dam/iwc/web/images/collections/pilot-watches/mark-xviii/IW327009/IW327009_front.png.transform.global_image_540_2x.png",
      "https://www.iwc.com/content/dam/iwc/web/images/collections/pilot-watches/mark-xviii/IW327009/IW327009_back.png.transform.global_image_540_2x.png",
    ],
    description:
      "A classic pilot's watch continuing the legendary Mark series with clean, functional design.",
  },
  {
    id: 1071,
    name: "Da Vinci Automatic",
    brand: "IWC",
    type: "Analog",
    price: "6950.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 66,
    rating: 4.4,
    imgs: [
      "https://www.iwc.com/content/dam/iwc/web/images/collections/davinci/iw356601/IW356601_front.png.transform.global_image_540_2x.png",
      "https://www.iwc.com/content/dam/iwc/web/images/collections/davinci/iw356601/IW356601_back.png.transform.global_image_540_2x.png",
    ],
    description:
      "An elegant round case design named after Leonardo da Vinci, with moonphase complication.",
  },
  {
    id: 1072,
    name: "Defy Classic",
    brand: "Zenith",
    type: "Analog",
    price: "6900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 68,
    rating: 4.4,
    imgs: [
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/9/5/95.9000.670-78.m9000_1.png",
      "https://www.zenith-watches.com/media/catalog/product/cache/c9e1b58ecc9c8184fae5f7f9ec6cf4f0/9/5/95.9000.670-78.m9000_2.png",
    ],
    description:
      "A contemporary sports watch featuring the faceted bezel and open-worked dial design.",
  },
  {
    id: 1073,
    name: "Patrimony",
    brand: "Vacheron Constantin",
    type: "Analog",
    price: "19500.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 80,
    rating: 4.8,
    imgs: [
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/20/1/1666201.png.crop.1000.1000.png",
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/20/2/1666202.png.crop.1000.1000.png",
    ],
    description:
      "Pure, refined elegance with clean lines representing the essence of Vacheron Constantin style.",
  },
  {
    id: 1074,
    name: "Historiques Triple Calendrier",
    brand: "Vacheron Constantin",
    type: "Analog",
    price: "45000.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 71,
    rating: 4.9,
    imgs: [
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/21/1/1666211.png.crop.1000.1000.png",
      "https://www.vacheron-constantin.com/dam/rcq/vac/16/66/21/2/1666212.png.crop.1000.1000.png",
    ],
    description:
      "A tribute to 1940s elegance with triple calendar and moonphase complications.",
  },
  {
    id: 1075,
    name: "L.U.C XPS",
    brand: "Chopard",
    type: "Analog",
    price: "11900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 67,
    rating: 4.6,
    imgs: [
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/168592-3001_1.png",
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/168592-3001_2.png",
    ],
    description:
      "An ultra-thin dress watch with Chopard's in-house L.U.C caliber and Côtes de Genève finishing.",
  },
  {
    id: 1076,
    name: "Mille Miglia GTS",
    brand: "Chopard",
    type: "Chronograph",
    price: "6650.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 70,
    rating: 4.4,
    imgs: [
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/168571-3001_1.png",
      "https://www.chopard.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/1/6/168571-3001_2.png",
    ],
    description:
      "A racing chronograph celebrating Chopard's partnership with the legendary Mille Miglia race.",
  },
  {
    id: 1077,
    name: "Laureato",
    brand: "Girard-Perregaux",
    type: "Analog",
    price: "12300.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 73,
    rating: 4.6,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/laureato-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/laureato-blue-back.png",
    ],
    description:
      "A luxury sports watch with octagonal bezel and integrated bracelet, designed in 1975.",
  },
  {
    id: 1078,
    name: "Code 11.59",
    brand: "Audemars Piguet",
    type: "Chronograph",
    price: "37000.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 75,
    rating: 4.7,
    imgs: [
      "https://www.audemarspiguet.com/content/dam/ap/com/products/watches/MTR010168.00/importer/watch.png.transform.appdpng.png",
      "https://www.audemarspiguet.com/content/dam/ap/com/products/watches/MTR010168.00/importer/caseback.png.transform.appdpng.png",
    ],
    description:
      "A modern interpretation featuring a complex case construction with octagonal middle and round bezel.",
  },
  {
    id: 1079,
    name: "Senator Excellence",
    brand: "Glashütte Original",
    type: "Analog",
    price: "9900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 65,
    rating: 4.5,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/senator-excellence-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/senator-excellence-blue-back.png",
    ],
    description:
      "German fine watchmaking with panorama date and the new Calibre 36 with silicon balance spring.",
  },
  {
    id: 1080,
    name: "SeaQ Panorama Date",
    brand: "Glashütte Original",
    type: "Analog",
    price: "10900.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 64,
    rating: 4.4,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/seaq-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/seaq-blue-back.png",
    ],
    description:
      "A dive watch inspired by the 1969 Spezimatic Type RP TS, with 200m water resistance.",
  },
  {
    id: 1081,
    name: "Avenger Automatic",
    brand: "Breitling",
    type: "Analog",
    price: "4250.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 74,
    rating: 4.4,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-9a8af0b3c2/a17318101c1a1-avenger-automatic-43-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2a2dca3f61/a17318101c1a1-avenger-automatic-43-702.png",
    ],
    description:
      "A bold aviation watch with high legibility, 300m water resistance, and robust construction.",
  },
  {
    id: 1082,
    name: "Premier B01 Chronograph",
    brand: "Breitling",
    type: "Chronograph",
    price: "8650.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 69,
    rating: 4.5,
    imgs: [
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-9a8af0b3c2/ab0118221g1p1-premier-b01-chronograph-42-rolled-up.png",
      "https://www.breitling.com/media/image/1/gallery_square_700/asset-version-2a2dca3f61/ab0118221g1p1-premier-b01-chronograph-42-702.png",
    ],
    description:
      "An elegant chronograph combining 1940s style with the modern B01 manufacture caliber.",
  },
  {
    id: 1083,
    name: "De Ville Prestige",
    brand: "Omega",
    type: "Analog",
    price: "2850.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 72,
    rating: 4.3,
    imgs: [
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-de-ville-prestige-co-axial-39-5-mm-42413402002001-l.png",
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-de-ville-prestige-co-axial-39-5-mm-42413402002001-2-product.png",
    ],
    description:
      "A refined dress watch embodying classic elegance with Roman numeral dial.",
  },
  {
    id: 1084,
    name: "Planet Ocean 600M",
    brand: "Omega",
    type: "Analog",
    price: "6800.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 84,
    rating: 4.7,
    imgs: [
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-seamaster-planet-ocean-600m-omega-co-axial-master-chronometer-43-5-mm-21530442103001-l.png",
      "https://www.omegawatches.com/media/catalog/product/cache/a5c37fddc1a529a1a44fea55d527b9a116f3738da3a2cc38006571a35a794cd5/o/m/omega-seamaster-planet-ocean-600m-omega-co-axial-master-chronometer-43-5-mm-21530442103001-2-product.png",
    ],
    description:
      "A professional dive watch with 600m water resistance and unidirectional ceramic bezel.",
  },
  {
    id: 1085,
    name: "GMT-Master II",
    brand: "Rolex",
    type: "Analog",
    price: "10700.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 96,
    rating: 4.9,
    imgs: [
      "https://content.rolex.com/dam/2022/upright-cc/m126710blro-0002.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com/dam/2022/laying-ba-with-shadow/m126710blro-0002.png?impolicy=v6-corners&sc=0.262",
    ],
    description:
      "The iconic GMT-Master II with bidirectional Cerachrom bezel in blue and red.",
  },
  {
    id: 1086,
    name: "Daytona",
    brand: "Rolex",
    type: "Chronograph",
    price: "14550.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 99,
    rating: 4.9,
    imgs: [
      "https://content.rolex.com/dam/2022/upright-cc/m126500ln-0001.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com/dam/2022/laying-ba-with-shadow/m126500ln-0001.png?impolicy=v6-corners&sc=0.262",
    ],
    description:
      "The legendary chronograph born on the racetracks, featuring the Cerachrom bezel and calibre 4131.",
  },
  {
    id: 1087,
    name: "Sky-Dweller",
    brand: "Rolex",
    type: "Analog",
    price: "16800.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 89,
    rating: 4.8,
    imgs: [
      "https://content.rolex.com/dam/2022/upright-cc/m336934-0001.png?impolicy=v6-corners&sc=0.384",
      "https://content.rolex.com/dam/2022/laying-ba-with-shadow/m336934-0001.png?impolicy=v6-corners&sc=0.262",
    ],
    description:
      "A sophisticated annual calendar with dual time zone, featuring the innovative Ring Command bezel.",
  },
  {
    id: 1088,
    name: "Dolce Vita",
    brand: "Longines",
    type: "Analog",
    price: "1350.00",
    movement: "Quartz",
    gender: "W",
    popularity: 63,
    rating: 4.2,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/5/l5.255.4.71.0_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/5/l5.255.4.71.0_2.png",
    ],
    description:
      "An elegant rectangular ladies' watch evoking the glamour of 1950s Italian cinema.",
  },
  {
    id: 1089,
    name: "Spirit",
    brand: "Longines",
    type: "Analog",
    price: "2350.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 71,
    rating: 4.4,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.810.4.93.6_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.810.4.93.6_2.png",
    ],
    description:
      "A pilot's watch honoring the pioneers of aviation with COSC-certified movement.",
  },
  {
    id: 1090,
    name: "Conquest V.H.P. GMT",
    brand: "Longines",
    type: "Analog",
    price: "1475.00",
    movement: "Quartz",
    gender: "M",
    popularity: 66,
    rating: 4.3,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.718.4.96.6_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.718.4.96.6_2.png",
    ],
    description:
      "A high-precision quartz with GMT function and perpetual calendar, accurate to +/- 5 seconds per year.",
  },
  {
    id: 1091,
    name: "Legend Diver",
    brand: "Longines",
    type: "Analog",
    price: "2525.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 75,
    rating: 4.5,
    imgs: [
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.774.4.50.0_1.png",
      "https://www.longines.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/3/l3.774.4.50.0_2.png",
    ],
    description:
      "A faithful reissue of the 1960s classic with internal rotating bezel and vintage styling.",
  },
  {
    id: 1092,
    name: "Supermarine",
    brand: "Bremont",
    type: "Analog",
    price: "4395.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 67,
    rating: 4.4,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/bremont-supermarine.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/bremont-supermarine-back.png",
    ],
    description:
      "A British-made dive watch inspired by the de Havilland Mosquito aircraft, water-resistant to 500m.",
  },
  {
    id: 1093,
    name: "MBII",
    brand: "Bremont",
    type: "Analog",
    price: "5195.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 65,
    rating: 4.3,
    imgs: [
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/bremont-mbii-blue.png",
      "https://cdn.shopify.com/s/files/1/0509/1864/6071/products/bremont-mbii-blue-back.png",
    ],
    description:
      "The official watch of Martin-Baker ejection seat pilots, built to survive ejection forces.",
  },
  {
    id: 1094,
    name: "Khaki Aviation X-Wind",
    brand: "Hamilton",
    type: "Chronograph",
    price: "1795.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 68,
    rating: 4.3,
    imgs: [
      "https://www.hamiltonwatch.com/media/catalog/product/h/7/h77912335_1.png",
      "https://www.hamiltonwatch.com/media/catalog/product/h/7/h77912335_2.png",
    ],
    description:
      "A pilot's watch with drift angle calculator for crosswind corrections during flight.",
  },
  {
    id: 1095,
    name: "Jazzmaster Open Heart",
    brand: "Hamilton",
    type: "Analog",
    price: "1095.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 73,
    rating: 4.4,
    imgs: [
      "https://www.hamiltonwatch.com/media/catalog/product/h/3/h32705551_1.png",
      "https://www.hamiltonwatch.com/media/catalog/product/h/3/h32705551_2.png",
    ],
    description:
      "An elegant dress watch with open heart dial revealing the automatic movement.",
  },
  {
    id: 1096,
    name: "Intra-Matic 68",
    brand: "Hamilton",
    type: "Chronograph",
    price: "2295.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 70,
    rating: 4.4,
    imgs: [
      "https://www.hamiltonwatch.com/media/catalog/product/h/3/h38716731_1.png",
      "https://www.hamiltonwatch.com/media/catalog/product/h/3/h38716731_2.png",
    ],
    description:
      "A vintage-inspired chronograph with panda dial and 60-hour power reserve.",
  },
  {
    id: 1097,
    name: "Star Classic",
    brand: "Rado",
    type: "Analog",
    price: "1250.00",
    movement: "Automatic & Mechanical",
    gender: "U",
    popularity: 61,
    rating: 4.1,
    imgs: [
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_star_561_0939_3_010_1.png",
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_star_561_0939_3_010_2.png",
    ],
    description:
      "The original Rado design icon from 1962, featuring a slim profile with vintage charm.",
  },
  {
    id: 1098,
    name: "DiaMaster",
    brand: "Rado",
    type: "Analog",
    price: "2100.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 64,
    rating: 4.2,
    imgs: [
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_diamaster_650_6060_3_016_1.png",
      "https://www.rado.com/media/catalog/product/r/g/rgb_cat_diamaster_650_6060_3_016_2.png",
    ],
    description:
      "A minimalist masterpiece combining high-tech ceramic with plasma technology.",
  },
  {
    id: 1099,
    name: "Seastar 1000",
    brand: "Tissot",
    type: "Analog",
    price: "675.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 73,
    rating: 4.4,
    imgs: [
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1204071704100_1.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/1/t1204071704100_2.jpg",
    ],
    description:
      "A professional dive watch with 300m water resistance, ceramic bezel, and helium escape valve.",
  },
  {
    id: 1100,
    name: "Chemin des Tourelles",
    brand: "Tissot",
    type: "Analog",
    price: "795.00",
    movement: "Automatic & Mechanical",
    gender: "M",
    popularity: 66,
    rating: 4.3,
    imgs: [
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/0/t0994071604800_1.jpg",
      "https://cdn.helioswatchstore.com/production/media/catalog/product/cache/dd1c3400e344f54d12df823ec560a116/t/0/t0994071604800_2.jpg",
    ],
    description:
      "A classic dress watch named after the street where Tissot was founded, featuring COSC certification.",
  },
];
// {
//     id: ,
//     name: "",
//     brand: "",
//     type: "",
//     price: "",
//     movement: "",
//     gender: "",
//     imgs: [
//         "","","","",
//     ],
//     description:
//       " ",
//   },
